[tgbot]
    token="7912131071:AAH-eBmgjQC4AX1X0_Hj_37PlWilI8cESZo"

[links]
    kate = "https://t.me/Kate_ritson"    


[yadisk]
    token = "y0__xD4oOhqGP7vNCDP2c-UEthN9zPWPjh9kWiZrCWUxA6syyiA"
    path = "/townpointbot/video/"

[postgres]
    url = "postgres://townpoint:townpoint@townpointdb:5432/townpoint?sslmode=disable"